### ISSUE TITLE
Add a copy of the MIT license to the repository

### ISSUE THREAD

**Issue by Calinou** [NovemberDev/godot_curvature_shader#1]
The asset submission says the asset's license is MIT. Please add a copy of the MIT license to the repository to confirm this :slightly_smiling_face:

**Comment by NovemberDev** [comment]
Sorry for leaving that out. I just added the MIT license to the repository

**Comment by Calinou** [comment]
Thanks! The asset is now approved on the asset library: https://godotengine.org/asset-library/asset/459
